# The include directory
INC=inc

# The Source Directory
SRC=src

# The Output
OUTPUT=ordered_list

# Compiler stuff
CPPFLAGS=-std=gnu++11 -I$(INC)

all:
	g++ $(CPPFLAGS) $(SRC)/*.c* -o $(OUTPUT)
